#ifndef RAYLIB_FUNCTIONS
#define RAYLIB_FUNCTIONS

#include <emscripten/bind.h>
#include <raylib-cpp.hpp>

using namespace emscripten;
void raylib_functions() {
    function("InitWindow", &raylib::InitWindow);
    function("WindowShouldClose", &WindowShouldClose);
    function("CloseWindow", &CloseWindow);
    function("IsWindowReady", &IsWindowReady);
    function("IsWindowFullscreen", &IsWindowFullscreen);
    function("IsWindowHidden", &IsWindowHidden);
    function("IsWindowMinimized", &IsWindowMinimized);
    function("IsWindowMaximized", &IsWindowMaximized);
    function("IsWindowFocused", &IsWindowFocused);
    function("IsWindowResized", &IsWindowResized);
    function("IsWindowState", &IsWindowState);
    function("SetWindowState", &SetWindowState);
    function("ClearWindowState", &ClearWindowState);
    function("ToggleFullscreen", &ToggleFullscreen);
    function("MaximizeWindow", &MaximizeWindow);
    function("MinimizeWindow", &MinimizeWindow);
    function("RestoreWindow", &RestoreWindow);
    function("SetWindowIcon", &SetWindowIcon);
    function("SetWindowTitle", &raylib::SetWindowTitle);
    function("SetWindowPosition", &SetWindowPosition);
    function("SetWindowMonitor", &SetWindowMonitor);
    function("SetWindowMinSize", &SetWindowMinSize);
    function("SetWindowSize", &SetWindowSize);
    // function("GetWindowHandle", &GetWindowHandle);
    function("GetScreenWidth", &GetScreenWidth);
    function("GetScreenHeight", &GetScreenHeight);
    function("GetMonitorCount", &GetMonitorCount);
    function("GetCurrentMonitor", &GetCurrentMonitor);
    function("GetMonitorPosition", &GetMonitorPosition);
    function("GetMonitorWidth", &GetMonitorWidth);
    function("GetMonitorHeight", &GetMonitorHeight);
    function("GetMonitorPhysicalWidth", &GetMonitorPhysicalWidth);
    function("GetMonitorPhysicalHeight", &GetMonitorPhysicalHeight);
    function("GetMonitorRefreshRate", &GetMonitorRefreshRate);
    function("GetWindowPosition", &GetWindowPosition);
    function("GetWindowScaleDPI", &GetWindowScaleDPI);
    function("GetMonitorName", &raylib::GetMonitorName);
    function("SetClipboardText", &raylib::SetClipboardText);
    function("GetClipboardText", &raylib::GetClipboardText);
    function("SwapScreenBuffer", &SwapScreenBuffer);
    function("PollInputEvents", &PollInputEvents);
    function("WaitTime", &WaitTime);
    function("ShowCursor", &ShowCursor);
    function("HideCursor", &HideCursor);
    function("IsCursorHidden", &IsCursorHidden);
    function("EnableCursor", &EnableCursor);
    function("DisableCursor", &DisableCursor);
    function("IsCursorOnScreen", &IsCursorOnScreen);
    function("ClearBackground", &ClearBackground);
    function("BeginDrawing", &BeginDrawing);
    function("EndDrawing", &EndDrawing);
    function("BeginMode2D", &BeginMode2D);
    function("EndMode2D", &EndMode2D);
    function("BeginMode3D", &BeginMode3D);
    function("EndMode3D", &EndMode3D);
    function("BeginTextureMode", &BeginTextureMode);
    function("EndTextureMode", &EndTextureMode);
    function("BeginShaderMode", &BeginShaderMode);
    function("EndShaderMode", &EndShaderMode);
    function("BeginBlendMode", &BeginBlendMode);
    function("EndBlendMode", &EndBlendMode);
    function("BeginScissorMode", &BeginScissorMode);
    function("EndScissorMode", &EndScissorMode);
    function("BeginVrStereoMode", &BeginVrStereoMode);
    function("EndVrStereoMode", &EndVrStereoMode);
    function("LoadVrStereoConfig", &LoadVrStereoConfig);
    function("UnloadVrStereoConfig", &UnloadVrStereoConfig);
    // function("LoadShader", &LoadShader);
    // function("LoadShaderFromMemory", &LoadShaderFromMemory);
    // function("GetShaderLocation", &GetShaderLocation);
    // function("GetShaderLocationAttrib", &GetShaderLocationAttrib);
    // function("SetShaderValue", &SetShaderValue);
    // function("SetShaderValueV", &SetShaderValueV);
    // function("SetShaderValueMatrix", &SetShaderValueMatrix);
    // function("SetShaderValueTexture", &SetShaderValueTexture);
    function("UnloadShader", &UnloadShader);
    function("GetMouseRay", &GetMouseRay);
    function("GetCameraMatrix", &GetCameraMatrix);
    function("GetCameraMatrix2D", &GetCameraMatrix2D);
    function("GetWorldToScreen", &GetWorldToScreen);
    function("GetWorldToScreenEx", &GetWorldToScreenEx);
    function("GetWorldToScreen2D", &GetWorldToScreen2D);
    function("GetScreenToWorld2D", &GetScreenToWorld2D);
    function("SetTargetFPS", &SetTargetFPS);
    function("GetFPS", &GetFPS);
    function("GetFrameTime", &GetFrameTime);
    function("GetTime", &GetTime);
    function("GetRandomValue", &GetRandomValue);
    function("SetRandomSeed", &SetRandomSeed);
    function("TakeScreenshot", &raylib::TakeScreenshot);
    function("SetConfigFlags", &SetConfigFlags);
    function("SetTraceLogLevel", &SetTraceLogLevel);
    // function("MemAlloc", &MemAlloc);
    // function("MemRealloc", &MemRealloc);
    // function("MemFree", &MemFree);
    // function("SetTraceLogCallback", &SetTraceLogCallback);
    // function("SetLoadFileDataCallback", &SetLoadFileDataCallback);
    // function("SetSaveFileDataCallback", &SetSaveFileDataCallback);
    // function("SetLoadFileTextCallback", &SetLoadFileTextCallback);
    // function("SetSaveFileTextCallback", &SetSaveFileTextCallback);
    //function("LoadFileData", &LoadFileData);
    // function("UnloadFileData", &UnloadFileData);
    //function("SaveFileData", &SaveFileData);
    function("LoadFileText", &raylib::LoadFileText);
    // function("UnloadFileText", &UnloadFileText);
    function("SaveFileText", &raylib::SaveFileText);
    function("FileExists", &raylib::FileExists);
    function("DirectoryExists", &raylib::DirectoryExists);
    function("IsFileExtension", &raylib::IsFileExtension);
    function("GetFileExtension", &raylib::GetFileExtension);
    function("GetFileName", &raylib::GetFileName);
    function("GetFileNameWithoutExt", &raylib::GetFileNameWithoutExt);
    function("GetDirectoryPath", &raylib::GetDirectoryPath);
    function("GetPrevDirectoryPath", &raylib::GetPrevDirectoryPath);
    function("GetWorkingDirectory", &raylib::GetWorkingDirectory);
    function("GetDirectoryFiles", &raylib::GetDirectoryFiles);
    function("ClearDirectoryFiles", &ClearDirectoryFiles);
    function("ChangeDirectory", &raylib::ChangeDirectory);
    function("IsFileDropped", &IsFileDropped);
    function("GetDroppedFiles", &raylib::GetDroppedFiles);
    function("ClearDroppedFiles", &ClearDroppedFiles);
    function("GetFileModTime", &raylib::GetFileModTime);
    // function("CompressData", &CompressData);
    // function("DecompressData", &DecompressData);
    // function("EncodeDataBase64", &EncodeDataBase64);
    // function("DecodeDataBase64", &DecodeDataBase64);
    function("SaveStorageValue", &SaveStorageValue);
    function("LoadStorageValue", &LoadStorageValue);
    function("OpenURL", &raylib::OpenURL);
    function("IsKeyPressed", &IsKeyPressed);
    function("IsKeyDown", &IsKeyDown);
    function("IsKeyReleased", &IsKeyReleased);
    function("IsKeyUp", &IsKeyUp);
    function("SetExitKey", &SetExitKey);
    function("GetKeyPressed", &GetKeyPressed);
    function("GetCharPressed", &GetCharPressed);
    function("IsGamepadAvailable", &IsGamepadAvailable);
    // function("GetGamepadName", &GetGamepadName);
    function("IsGamepadButtonPressed", &IsGamepadButtonPressed);
    function("IsGamepadButtonDown", &IsGamepadButtonDown);
    function("IsGamepadButtonReleased", &IsGamepadButtonReleased);
    function("IsGamepadButtonUp", &IsGamepadButtonUp);
    function("GetGamepadButtonPressed", &GetGamepadButtonPressed);
    function("GetGamepadAxisCount", &GetGamepadAxisCount);
    function("GetGamepadAxisMovement", &GetGamepadAxisMovement);
    //function("SetGamepadMappings", &SetGamepadMappings);
    function("IsMouseButtonPressed", &IsMouseButtonPressed);
    function("IsMouseButtonDown", &IsMouseButtonDown);
    function("IsMouseButtonReleased", &IsMouseButtonReleased);
    function("IsMouseButtonUp", &IsMouseButtonUp);
    function("GetMouseX", &GetMouseX);
    function("GetMouseY", &GetMouseY);
    function("GetMousePosition", &GetMousePosition);
    function("GetMouseDelta", &GetMouseDelta);
    function("SetMousePosition", &SetMousePosition);
    function("SetMouseOffset", &SetMouseOffset);
    function("SetMouseScale", &SetMouseScale);
    function("GetMouseWheelMove", &GetMouseWheelMove);
    function("SetMouseCursor", &SetMouseCursor);
    function("GetTouchX", &GetTouchX);
    function("GetTouchY", &GetTouchY);
    function("GetTouchPosition", &GetTouchPosition);
    function("GetTouchPointId", &GetTouchPointId);
    function("GetTouchPointCount", &GetTouchPointCount);
    function("SetGesturesEnabled", &SetGesturesEnabled);
    function("IsGestureDetected", &IsGestureDetected);
    function("GetGestureDetected", &GetGestureDetected);
    function("GetGestureHoldDuration", &GetGestureHoldDuration);
    function("GetGestureDragVector", &GetGestureDragVector);
    function("GetGestureDragAngle", &GetGestureDragAngle);
    function("GetGesturePinchVector", &GetGesturePinchVector);
    function("GetGesturePinchAngle", &GetGesturePinchAngle);
    function("SetCameraMode", &SetCameraMode);
    function("UpdateCamera", &raylib::UpdateCamera);
    function("SetCameraPanControl", &SetCameraPanControl);
    function("SetCameraAltControl", &SetCameraAltControl);
    function("SetCameraSmoothZoomControl", &SetCameraSmoothZoomControl);
    function("SetCameraMoveControls", &SetCameraMoveControls);
    function("SetShapesTexture", &SetShapesTexture);
    function("DrawPixel", &DrawPixel);
    function("DrawPixelV", &DrawPixelV);
    function("DrawLine", &DrawLine);
    function("DrawLineV", &DrawLineV);
    function("DrawLineEx", &DrawLineEx);
    function("DrawLineBezier", &DrawLineBezier);
    function("DrawLineBezierQuad", &DrawLineBezierQuad);
    function("DrawLineBezierCubic", &DrawLineBezierCubic);
    // function("DrawLineStrip", &DrawLineStrip);
    function("DrawCircle", &DrawCircle);
    function("DrawCircleSector", &DrawCircleSector);
    function("DrawCircleSectorLines", &DrawCircleSectorLines);
    function("DrawCircleGradient", &DrawCircleGradient);
    function("DrawCircleV", &DrawCircleV);
    function("DrawCircleLines", &DrawCircleLines);
    function("DrawEllipse", &DrawEllipse);
    function("DrawEllipseLines", &DrawEllipseLines);
    function("DrawRing", &DrawRing);
    function("DrawRingLines", &DrawRingLines);
    function("DrawRectangle", &DrawRectangle);
    function("DrawRectangleV", &DrawRectangleV);
    function("DrawRectangleRec", &DrawRectangleRec);
    function("DrawRectanglePro", &DrawRectanglePro);
    function("DrawRectangleGradientV", &DrawRectangleGradientV);
    function("DrawRectangleGradientH", &DrawRectangleGradientH);
    function("DrawRectangleGradientEx", &DrawRectangleGradientEx);
    function("DrawRectangleLines", &DrawRectangleLines);
    function("DrawRectangleLinesEx", &DrawRectangleLinesEx);
    function("DrawRectangleRounded", &DrawRectangleRounded);
    function("DrawRectangleRoundedLines", &DrawRectangleRoundedLines);
    function("DrawTriangle", &DrawTriangle);
    function("DrawTriangleLines", &DrawTriangleLines);
    // function("DrawTriangleFan", &DrawTriangleFan);
    // function("DrawTriangleStrip", &DrawTriangleStrip);
    function("DrawPoly", &DrawPoly);
    function("DrawPolyLines", &DrawPolyLines);
    function("DrawPolyLinesEx", &DrawPolyLinesEx);
    function("CheckCollisionRecs", &CheckCollisionRecs);
    function("CheckCollisionCircles", &CheckCollisionCircles);
    function("CheckCollisionCircleRec", &CheckCollisionCircleRec);
    function("CheckCollisionPointRec", &CheckCollisionPointRec);
    function("CheckCollisionPointCircle", &CheckCollisionPointCircle);
    function("CheckCollisionPointTriangle", &CheckCollisionPointTriangle);
    // function("CheckCollisionLines", &CheckCollisionLines);
    function("CheckCollisionPointLine", &CheckCollisionPointLine);
    function("GetCollisionRec", &GetCollisionRec);
    // function("LoadImage", &raylib::LoadImage);
    // function("LoadImageRaw", &raylib::LoadImageRaw);
    // function("LoadImageAnim", &raylib::LoadImageAnim);
    // function("LoadImageFromMemory", &raylib::LoadImageFromMemory);
    // function("LoadImageFromTexture", &LoadImageFromTexture);
    // function("LoadImageFromScreen", &LoadImageFromScreen);
    function("UnloadImage", &UnloadImage);
    // function("ExportImage", &raylib::ExportImage);
    // function("ExportImageAsCode", &raylib::ExportImageAsCode);
    function("GenImageColor", &GenImageColor);
    function("GenImageGradientV", &GenImageGradientV);
    function("GenImageGradientH", &GenImageGradientH);
    function("GenImageGradientRadial", &GenImageGradientRadial);
    function("GenImageChecked", &GenImageChecked);
    function("GenImageWhiteNoise", &GenImageWhiteNoise);
    function("GenImageCellular", &GenImageCellular);
    function("ImageCopy", &ImageCopy);
    function("ImageFromImage", &ImageFromImage);
    // function("ImageText", &ImageText);
    // function("ImageTextEx", &ImageTextEx);
    // function("ImageFormat", &ImageFormat);
    // function("ImageToPOT", &ImageToPOT);
    // function("ImageCrop", &ImageCrop);
    // function("ImageAlphaCrop", &ImageAlphaCrop);
    // function("ImageAlphaClear", &ImageAlphaClear);
    // function("ImageAlphaMask", &ImageAlphaMask);
    function("ImageAlphaPremultiply", &ImageAlphaPremultiply, allow_raw_pointers());
    function("ImageResize", &ImageResize, allow_raw_pointers());
    function("ImageResizeNN", &ImageResizeNN, allow_raw_pointers());
    function("ImageResizeCanvas", &ImageResizeCanvas, allow_raw_pointers());
    function("ImageMipmaps", &ImageMipmaps, allow_raw_pointers());
    function("ImageDither", &ImageDither, allow_raw_pointers());
    function("ImageFlipVertical", &ImageFlipVertical, allow_raw_pointers());
    function("ImageFlipHorizontal", &ImageFlipHorizontal, allow_raw_pointers());
    function("ImageRotateCW", &ImageRotateCW, allow_raw_pointers());
    function("ImageRotateCCW", &ImageRotateCCW, allow_raw_pointers());
    function("ImageColorTint", &ImageColorTint, allow_raw_pointers());
    function("ImageColorInvert", &ImageColorInvert, allow_raw_pointers());
    function("ImageColorGrayscale", &ImageColorGrayscale, allow_raw_pointers());
    function("ImageColorContrast", &ImageColorContrast, allow_raw_pointers());
    function("ImageColorBrightness", &ImageColorBrightness, allow_raw_pointers());
    function("ImageColorReplace", &ImageColorReplace, allow_raw_pointers());
    // function("LoadImageColors", &LoadImageColors);
    // function("LoadImagePalette", &LoadImagePalette);
    // function("UnloadImageColors", &UnloadImageColors);
    // function("UnloadImagePalette", &UnloadImagePalette);
    function("GetImageAlphaBorder", &GetImageAlphaBorder);
    function("GetImageColor", &GetImageColor);
    function("ImageClearBackground", &ImageClearBackground, allow_raw_pointers());
    function("ImageDrawPixel", &ImageDrawPixel, allow_raw_pointers());
    function("ImageDrawPixelV", &ImageDrawPixelV, allow_raw_pointers());
    function("ImageDrawLine", &ImageDrawLine, allow_raw_pointers());
    function("ImageDrawLineV", &ImageDrawLineV, allow_raw_pointers());
    function("ImageDrawCircle", &ImageDrawCircle, allow_raw_pointers());
    function("ImageDrawCircleV", &ImageDrawCircleV, allow_raw_pointers());
    function("ImageDrawRectangle", &ImageDrawRectangle, allow_raw_pointers());
    function("ImageDrawRectangleV", &ImageDrawRectangleV, allow_raw_pointers());
    function("ImageDrawRectangleRec", &ImageDrawRectangleRec, allow_raw_pointers());
    function("ImageDrawRectangleLines", &ImageDrawRectangleLines, allow_raw_pointers());
    function("ImageDraw", &ImageDraw, allow_raw_pointers());
    // function("ImageDrawText", &ImageDrawText, allow_raw_pointers());
    // function("ImageDrawTextEx", &ImageDrawTextEx, allow_raw_pointers());
    // function("LoadTexture", &LoadTexture);
    function("LoadTextureFromImage", &LoadTextureFromImage);
    function("LoadTextureCubemap", &LoadTextureCubemap);
    function("LoadRenderTexture", &LoadRenderTexture);
    function("UnloadTexture", &UnloadTexture);
    function("UnloadRenderTexture", &UnloadRenderTexture);
    // function("UpdateTexture", &UpdateTexture);
    // function("UpdateTextureRec", &UpdateTextureRec);
    // function("GenTextureMipmaps", &GenTextureMipmaps);
    // function("SetTextureFilter", &SetTextureFilter);
    // function("SetTextureWrap", &SetTextureWrap);
    function("DrawTexture", &DrawTexture);
    function("DrawTextureV", &DrawTextureV);
    function("DrawTextureEx", &DrawTextureEx);
    function("DrawTextureRec", &DrawTextureRec);
    function("DrawTextureQuad", &DrawTextureQuad);
    function("DrawTextureTiled", &DrawTextureTiled);
    function("DrawTexturePro", &DrawTexturePro);
    function("DrawTextureNPatch", &DrawTextureNPatch);
    //function("DrawTexturePoly", &DrawTexturePoly);
    function("Fade", &Fade);
    function("ColorToInt", &ColorToInt);
    function("ColorNormalize", &ColorNormalize);
    function("ColorFromNormalized", &ColorFromNormalized);
    function("ColorToHSV", &ColorToHSV);
    function("ColorFromHSV", &ColorFromHSV);
    function("ColorAlpha", &ColorAlpha);
    function("ColorAlphaBlend", &ColorAlphaBlend);
    function("GetColor", &GetColor);
    // function("GetPixelColor", &GetPixelColor);
    // function("SetPixelColor", &SetPixelColor);
    function("GetPixelDataSize", &GetPixelDataSize);
    function("GetFontDefault", &GetFontDefault);
    //function("LoadFont", &LoadFont);
    //function("LoadFontEx", &LoadFontEx);
    function("LoadFontFromImage", &LoadFontFromImage);
    //function("LoadFontFromMemory", &LoadFontFromMemory);
    //function("LoadFontData", &LoadFontData);
    // function("GenImageFontAtlas", &GenImageFontAtlas);
    // function("UnloadFontData", &UnloadFontData);
    function("UnloadFont", &UnloadFont);
    function("DrawFPS", &DrawFPS);
    // function("DrawText", &DrawText);
    // function("DrawTextEx", &DrawTextEx);
    // function("DrawTextPro", &DrawTextPro);
    // function("DrawTextCodepoint", &DrawTextCodepoint);
    // function("MeasureText", &MeasureText);
    // function("MeasureTextEx", &MeasureTextEx);
    function("GetGlyphIndex", &GetGlyphIndex);
    function("GetGlyphInfo", &GetGlyphInfo);
    function("GetGlyphAtlasRec", &GetGlyphAtlasRec);
    // function("LoadCodepoints", &LoadCodepoints);
    // function("UnloadCodepoints", &UnloadCodepoints);
    // function("GetCodepointCount", &GetCodepointCount);
    // function("GetCodepoint", &GetCodepoint);
    // function("CodepointToUTF8", &CodepointToUTF8);
    // function("TextCodepointsToUTF8", &TextCodepointsToUTF8);
    // function("TextCopy", &TextCopy);
    // function("TextIsEqual", &TextIsEqual);
    // function("TextLength", &TextLength);
    // function("TextFormat", &TextFormat);
    // function("TextSubtext", &TextSubtext);
    // function("TextReplace", &TextReplace);
    // function("TextInsert", &TextInsert);
    // function("TextJoin", &TextJoin);
    // function("TextSplit", &TextSplit);
    // function("TextAppend", &TextAppend);
    // function("TextFindIndex", &TextFindIndex);
    // function("TextToUpper", &TextToUpper);
    // function("TextToLower", &TextToLower);
    // function("TextToPascal", &TextToPascal);
    // function("TextToInteger", &TextToInteger);
    function("DrawLine3D", &DrawLine3D);
    function("DrawPoint3D", &DrawPoint3D);
    function("DrawCircle3D", &DrawCircle3D);
    function("DrawTriangle3D", &DrawTriangle3D);
    // function("DrawTriangleStrip3D", &DrawTriangleStrip3D);
    function("DrawCube", &DrawCube);
    function("DrawCubeV", &DrawCubeV);
    function("DrawCubeWires", &DrawCubeWires);
    function("DrawCubeWiresV", &DrawCubeWiresV);
    function("DrawCubeTexture", &DrawCubeTexture);
    function("DrawCubeTextureRec", &DrawCubeTextureRec);
    function("DrawSphere", &DrawSphere);
    function("DrawSphereEx", &DrawSphereEx);
    function("DrawSphereWires", &DrawSphereWires);
    function("DrawCylinder", &DrawCylinder);
    function("DrawCylinderEx", &DrawCylinderEx);
    function("DrawCylinderWires", &DrawCylinderWires);
    function("DrawCylinderWiresEx", &DrawCylinderWiresEx);
    function("DrawPlane", &DrawPlane);
    function("DrawRay", &DrawRay);
    function("DrawGrid", &DrawGrid);
    // function("LoadModel", &LoadModel);
    function("LoadModelFromMesh", &LoadModelFromMesh);
    function("UnloadModel", &UnloadModel);
    function("UnloadModelKeepMeshes", &UnloadModelKeepMeshes);
    function("GetModelBoundingBox", &GetModelBoundingBox);
    function("DrawModel", &DrawModel);
    function("DrawModelEx", &DrawModelEx);
    function("DrawModelWires", &DrawModelWires);
    function("DrawModelWiresEx", &DrawModelWiresEx);
    function("DrawBoundingBox", &DrawBoundingBox);
    function("DrawBillboard", &DrawBillboard);
    function("DrawBillboardRec", &DrawBillboardRec);
    function("DrawBillboardPro", &DrawBillboardPro);
    // function("UploadMesh", &UploadMesh);
    // function("UpdateMeshBuffer", &UpdateMeshBuffer);
    function("UnloadMesh", &UnloadMesh);
    function("DrawMesh", &DrawMesh);
    // function("DrawMeshInstanced", &DrawMeshInstanced);
    // function("ExportMesh", &ExportMesh);
    function("GetMeshBoundingBox", &GetMeshBoundingBox);
    // function("GenMeshTangents", &GenMeshTangents);
    // function("GenMeshBinormals", &GenMeshBinormals);
    function("GenMeshPoly", &GenMeshPoly);
    function("GenMeshPlane", &GenMeshPlane);
    function("GenMeshCube", &GenMeshCube);
    function("GenMeshSphere", &GenMeshSphere);
    function("GenMeshHemiSphere", &GenMeshHemiSphere);
    function("GenMeshCylinder", &GenMeshCylinder);
    function("GenMeshCone", &GenMeshCone);
    function("GenMeshTorus", &GenMeshTorus);
    function("GenMeshKnot", &GenMeshKnot);
    function("GenMeshHeightmap", &GenMeshHeightmap);
    function("GenMeshCubicmap", &GenMeshCubicmap);
    // function("LoadMaterials", &LoadMaterials);
    function("LoadMaterialDefault", &LoadMaterialDefault);
    function("UnloadMaterial", &UnloadMaterial);
    // function("SetMaterialTexture", &SetMaterialTexture);
    // function("SetModelMeshMaterial", &SetModelMeshMaterial);
    // function("LoadModelAnimations", &LoadModelAnimations);
    function("UpdateModelAnimation", &UpdateModelAnimation);
    function("UnloadModelAnimation", &UnloadModelAnimation);
    // function("UnloadModelAnimations", &UnloadModelAnimations);
    function("IsModelAnimationValid", &IsModelAnimationValid);
    function("CheckCollisionSpheres", &CheckCollisionSpheres);
    function("CheckCollisionBoxes", &CheckCollisionBoxes);
    function("CheckCollisionBoxSphere", &CheckCollisionBoxSphere);
    function("GetRayCollisionSphere", &GetRayCollisionSphere);
    function("GetRayCollisionBox", &GetRayCollisionBox);
    function("GetRayCollisionModel", &GetRayCollisionModel);
    function("GetRayCollisionMesh", &GetRayCollisionMesh);
    function("GetRayCollisionTriangle", &GetRayCollisionTriangle);
    function("GetRayCollisionQuad", &GetRayCollisionQuad);
    function("InitAudioDevice", &InitAudioDevice);
    function("CloseAudioDevice", &CloseAudioDevice);
    function("IsAudioDeviceReady", &IsAudioDeviceReady);
    function("SetMasterVolume", &SetMasterVolume);
    // function("LoadWave", &LoadWave);
    // function("LoadWaveFromMemory", &LoadWaveFromMemory);
    // function("LoadSound", &LoadSound);
    // function("LoadSoundFromWave", &LoadSoundFromWave);
    // function("UpdateSound", &UpdateSound);
    function("UnloadWave", &UnloadWave);
    function("UnloadSound", &UnloadSound);
    // function("ExportWave", &ExportWave);
    // function("ExportWaveAsCode", &ExportWaveAsCode);
    function("PlaySound", &PlaySound);
    function("StopSound", &StopSound);
    function("PauseSound", &PauseSound);
    function("ResumeSound", &ResumeSound);
    function("PlaySoundMulti", &PlaySoundMulti);
    function("StopSoundMulti", &StopSoundMulti);
    function("GetSoundsPlaying", &GetSoundsPlaying);
    function("IsSoundPlaying", &IsSoundPlaying);
    function("SetSoundVolume", &SetSoundVolume);
    function("SetSoundPitch", &SetSoundPitch);
    // function("WaveFormat", &WaveFormat);
    function("WaveCopy", &WaveCopy);
    // function("WaveCrop", &WaveCrop);
    // function("LoadWaveSamples", &LoadWaveSamples);
    // function("UnloadWaveSamples", &UnloadWaveSamples);
    // function("LoadMusicStream", &LoadMusicStream);
    // function("LoadMusicStreamFromMemory", &LoadMusicStreamFromMemory);
    function("UnloadMusicStream", &UnloadMusicStream);
    function("PlayMusicStream", &PlayMusicStream);
    function("IsMusicStreamPlaying", &IsMusicStreamPlaying);
    function("UpdateMusicStream", &UpdateMusicStream);
    function("StopMusicStream", &StopMusicStream);
    function("PauseMusicStream", &PauseMusicStream);
    function("ResumeMusicStream", &ResumeMusicStream);
    function("SeekMusicStream", &SeekMusicStream);
    function("SetMusicVolume", &SetMusicVolume);
    function("SetMusicPitch", &SetMusicPitch);
    function("GetMusicTimeLength", &GetMusicTimeLength);
    function("GetMusicTimePlayed", &GetMusicTimePlayed);
    function("LoadAudioStream", &LoadAudioStream);
    function("UnloadAudioStream", &UnloadAudioStream);
    // function("UpdateAudioStream", &UpdateAudioStream);
    function("IsAudioStreamProcessed", &IsAudioStreamProcessed);
    function("PlayAudioStream", &PlayAudioStream);
    function("PauseAudioStream", &PauseAudioStream);
    function("ResumeAudioStream", &ResumeAudioStream);
    function("IsAudioStreamPlaying", &IsAudioStreamPlaying);
    function("StopAudioStream", &StopAudioStream);
    function("SetAudioStreamVolume", &SetAudioStreamVolume);
    function("SetAudioStreamPitch", &SetAudioStreamPitch);
    function("SetAudioStreamBufferSizeDefault", &SetAudioStreamBufferSizeDefault);


}

#endif
